apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app
  namespace: myapp-pull
  labels:
    app: my-java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: my-java-app
          image: europe-west2-docker.pkg.dev/tcp-demo/tcp-demo-repo/tcp-demo-app:d611b4d
          ports:
            - containerPort: 8080
